# Use an official Node.js runtime as a parent image
FROM node:22.9.0

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Copy the .env and .env.development files
COPY .env ./

# Build the TypeScript code
RUN npm run build

# Expose the port on which the app will run
EXPOSE 3000

# Start the app
CMD ["node", "dist/main"]
